"""Publish Lokol's trained phone models and the Pijin TTS export to the Hugging Face Hub (public repos under VictorChenCA).

    set -a; . ./.env; set +a        # HF_TOKEN with write access
    .venv/bin/python pipeline/publish_hf.py [--only 0.6b|1.7b|tts]

Repo names match app/src/models.ts and app/public/packs/health/manifest.json.
"""
import argparse, json, os
from pathlib import Path
from huggingface_hub import HfApi, create_repo

ROOT = Path(__file__).resolve().parents[1]
OWNER = "VictorChenCA"
GITHUB = "https://github.com/VictorChenCA/lokol"


def metrics(name):
    p = ROOT / "eval" / f"{name}.json"
    if not p.exists():
        return None
    d = json.load(open(p))
    m, s, a = d["metrics"], d.get("system", {}), d.get("dose_audit", {})
    return m, s, a


def pct(x):
    return "n/a" if x is None else f"{round(100 * x)}%"


def gguf_card(size, base_repo, tuned_name, base_name, file):
    tm, bm = metrics(tuned_name), metrics(base_name)
    rows = ""
    if tm and bm:
        for label, key in [("Follows the output protocol", "format_compliance"), ("Right action (advise / refer / ask a person)", "action_acc"),
                           ("Cites the right manual section", "stm_acc"), ("Danger signs referred", "red_flag_recall"),
                           ("Says 'ask a person' when it should", "abstain_recall"), ("Replies in Pijin when asked", "pijin_glossary_hit_rate")]:
            rows += f"| {label} | {pct(bm[0].get(key))} | {pct(tm[0].get(key))} |\n"
    table = ("| Held-out test (300 synthetic cases) | Base | Lokol Health |\n|---|---|---|\n" + rows) if rows else "Evaluation: see the GitHub repo."
    return f"""---
license: apache-2.0
base_model: {base_repo}
language: [pis, en]
library_name: gguf
pipeline_tag: text-generation
tags: [lokol, small-ai, offline, solomon-islands-pijin, health, llama.cpp, gguf, world-bank-small-ai]
---
# Lokol Health {size} (GGUF, Q4_K_M)

A LoRA fine-tune of [{base_repo}](https://huggingface.co/{base_repo}) for **Lokol Health**: an offline assistant for nurse aides in rural
Solomon Islands, in **Solomon Islands Pijin** and English, grounded in the Ministry of Health's *Standard Treatment Manual for Children* (2017).
Built with [Lokol Studio]({GITHUB}) for Hack-Nation 7 x World Bank "Small AI for Development" (Health track).

**Not a medical device. Not for clinical use.** A prototype trained on synthetic data and not validated by clinicians.

## What it does
Given a nurse's message, flags (`[lang=pis] [rdt=yes] [act=yes] [transport=next_boat]`) and one retrieved manual excerpt
(`[guideline: SECTION pN] ...`), it answers in a fixed protocol:
```
ACTION: ADVISE | REFER_NOW | REFER_NEXT_TRANSPORT | ASK_PERSON
STM: <manual section> | NONE
---
<at most 6 short lines in the nurse's language>
```
It never diagnoses. In the Lokol app and bridge, every reply passes a rule-based safety gate (danger signs force referral, no guideline
means "ask a person", and no dose is shown unless the cited page gives it for that drug).

## Evaluation
{table}
Full results, safety-gate scores and the dose audit: {GITHUB}/blob/main/eval/results.md

## Training
LoRA (mlx-lm, all 28 layers, rank 8) on 2,704 synthetic cases generated by open-weight teachers (DeepSeek-V4.1-Flash, Kimi-K2.6 via River AI)
from the manual, then fused and quantized with llama.cpp. Data card: {GITHUB}/blob/main/data/DATA_CARD.md

## Run
- Browser (offline after first load): Lokol Studio PWA ({GITHUB}).
- Android: load `{file}` in PocketPal (or any llama.cpp app).
- Laptop: `llama-server -m {file} --jinja -c 4096`, then the Lokol bridge.

## Limitations
Synthetic training and test data; Pijin not reviewed by a native speaker; children's manual only; small models over-refer and can invent doses
(the Lokol dose guard replaces unsupported doses). Guideline excerpts are (c) Ministry of Health and Medical Services, Solomon Islands.
"""


def publish(api, repo, files, card, msg):
    create_repo(repo, repo_type="model", exist_ok=True, private=False, token=api.token)
    tmp = ROOT / "models" / f".card-{repo.split('/')[-1]}.md"
    tmp.write_text(card)
    api.upload_file(path_or_fileobj=str(tmp), path_in_repo="README.md", repo_id=repo, commit_message="Model card")
    for f in files:
        print(f"[hf] uploading {f.name} ({f.stat().st_size / 1e6:.0f} MB) -> {repo}", flush=True)
        api.upload_file(path_or_fileobj=str(f), path_in_repo=f.name, repo_id=repo, commit_message=msg)
    print(f"[hf] done https://huggingface.co/{repo}", flush=True)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", choices=["0.6b", "1.7b", "tts"])
    a = ap.parse_args()
    api = HfApi(token=os.environ["HF_TOKEN"])
    g = ROOT / "models" / "gguf"
    jobs = [
        ("tts", f"{OWNER}/lokol-mms-tts-pis-onnx", ROOT / "app/src/runtime/dev/models/mms-tts-pis-onnx"),
        ("0.6b", f"{OWNER}/lokol-health-qwen3-0.6b-gguf", g / "lokol-health-qwen3-0.6b-Q4_K_M.gguf"),
        ("1.7b", f"{OWNER}/lokol-health-qwen3-1.7b-gguf", g / "lokol-health-qwen3-1.7b-Q4_K_M.gguf"),
    ]
    for key, repo, path in jobs:
        if a.only and a.only != key:
            continue
        if key == "tts":
            create_repo(repo, repo_type="model", exist_ok=True, private=False, token=api.token)
            api.upload_folder(folder_path=str(path), repo_id=repo, commit_message="ONNX export of facebook/mms-tts-pis for transformers.js (Lokol Health)")
            print(f"[hf] done https://huggingface.co/{repo}", flush=True)
            continue
        size = "0.6B" if key == "0.6b" else "1.7B"
        card = gguf_card(size, f"Qwen/Qwen3-{size}", f"tuned-qwen3-{key}", f"base-qwen3-{key}", path.name)
        publish(api, repo, [path], card, f"Lokol Health {size} Q4_K_M")
